name: Update WC Scores/Leaderboard

on:
  schedule:
    - cron: '15 13-23 * 6 *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    env: 
      API_TOKEN_FOOTBALL: ${{ secrets.API_TOKEN_FOOTBALL }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      NAME_MAP: ${{ secrets.NAME_MAP }}
      NEON_HOST: ${{ secrets.NEON_HOST }}
      NEON_PASSWORD: ${{ secrets.NEON_PASSWORD }}
      NEON_PORT: ${{ secrets.NEON_PORT }}
      NEON_USER: ${{ secrets.NEON_USER }}
      SHEET_ID: ${{ secrets.SHEET_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.14'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run update_results
        run: python -m pipelines.update_results

      - name: Run scoring_pipeline
        run: python -m pipelines.scoring_pipeline